TYPO3:
  Flow:
    error:
      exceptionHandler:
        className: 'Networkteam\SentryClient\Handler\ProductionExceptionHandler'

    object:
      excludeClasses:
        'monolog.monolog': ['.*']
        'sentry.sentry': ['.*']

Networkteam:
  SentryClient:
    # The Sentry DSN
    dsn: ''
    release: '%env:FLOW_RELEASE%'
